const BaseController = require('../controllers/base');
const ValidatorController = require('../controllers/validator');
const UserController = require('../controllers/user');
const BannerController = require('../controllers/banner');
const ArticleController = require('../controllers/article');
const TagController = require('../controllers/tag');
const CategoryController = require('../controllers/category');
const CommentController = require('../controllers/comment');
const ReplyController = require('../controllers/reply');
const ChatgptController = require('../controllers/chatgpt');
const AgentController = require('../controllers/agent');
const PetAgentController = require('../controllers/pet-agent');
const UploadController = require('../controllers/upload');
const { authLimiter, uploadLimiter, agentLimiter } = require('../utils/rate-limit');

module.exports = function(app) {
	app.use(BaseController);
	app.use('/validator/img_code', authLimiter);
	app.use('/user/login', authLimiter);
	app.use('/user/register', authLimiter);
	app.use('/user/forgetpwd', authLimiter);
	app.use('/upload/image', uploadLimiter);
	app.use('/pet-agent', agentLimiter);
	app.use('/validator', ValidatorController);
	app.use('/user', UserController);
	app.use('/banner', BannerController);
	app.use('/article', ArticleController);
	app.use('/tag', TagController);
	app.use('/category', CategoryController);
	app.use('/comment', CommentController);
	app.use('/reply', ReplyController);
	app.use('/chatgpt', ChatgptController);
	app.use('/agent', AgentController);
	app.use('/pet-agent', PetAgentController);
	app.use('/upload', UploadController);
};
